### ISSUE TITLE
For some files, reports internal error

### ISSUE THREAD

**Issue by neurolabusc** [dougallj/zlib-dougallj#3]
The zlib fails to decompress some files, even though it created them and gzip can decompress them:

```
git clone https://github.com/dougallj/zlib-dougallj.git
cd zlib-dougallj
mkdir build; cd build
cmake  -DBUILD_EXAMPLES=ON ..; make
curl -fLO https://github.com/MiloszKrajewski/SilesiaCorpus/raw/master/mr.zip
unzip mr.zip 
./minigzip mr
./minigzip -d  mr.gz
./minigzip: mr.gz: internal error: inflate stream corrupt
```

Note this bug was introduced in this branch, and is not seen in the source cloudflare zlib:

```
git clone https://github.com/cloudflare/zlib.git
cd zlib
mkdir build; cd build
cmake  -DBUILD_EXAMPLES=ON ..; make
curl -fLO https://github.com/MiloszKrajewski/SilesiaCorpus/raw/master/mr.zip
unzip mr.zip 
./minigzip mr
./minigzip -d  mr.gz
```

**Comment by dougallj** [comment]
I've reverted the latest commit, which appears to have introduced this bug, though I haven't diagnosed the issue. Let me know if you still have issues on latest.

**Comment by neurolabusc** [comment]
Thanks. This change allows your code [to pass my validation test](https://github.com/neurolabusc/zlib-bench-python/tree/dougallj) which ensures that each tool can decompress all files from the silesia corpus as compressed by each of the tools. It not only tests speed, but also ensures a accurate decompression.

The gains are not as big as you originally reported, simply because [others have adopted some of your optimizations](https://github.com/cloudflare/zlib/pull/40):

| DecompressMethod | Min   | Mean  | Max   | mb/s   |
|------------------|-------|-------|-------|--------|
| zlibCF           | 17393 | 17820 | 18546 | 438.68 |
| zlibDJ           | 13578 | 13590 | 13613 | 561.94 |
| zlibMadler       | 46714 | 46798 | 46905 | 163.33 |
| zlibNG           | 14924 | 14965 | 15010 | 511.25 |

To run this script, you would run the following commands:

```
git clone --branch dougallj git@github.com:neurolabusc/zlib-bench-python.git
cd zlib-bench-python 
python a_compile.py
python b_speed_test.py
```
